### ISSUE TITLE
Please ping me on this issue if this APP is released.

### ISSUE THREAD

**Issue by SpongeBobSun** [fmoraldo-mithraw/rateyourday#105]
Please ping me on this issue if this APP is released. 

I want to maintain a list of APPs which using `MCalendarView`. 

Thanks!

**Comment by fmoraldo-mithraw** [comment]
@SpongeBobSun it's released : https://play.google.com/store/apps/details?id=com.mithraw.howwasyourday

I've made one more fix for my branch lately, i have to push it before making another pull request, i will be doing it soon :)
